### ISSUE TITLE
Undefined variables inside React component callbacks have a wrong type

### ISSUE THREAD

**Issue by bsansouci** [rescript-lang/rescript-editor-support#14]
It seems like if I have a callback in my react component, I can reference undefined variables without the extension seeing a problem and it even has a type:
```rescript
Js.Fn.arity1<
  option<React.element> => unit
>
type arity1<'a> = {I1: 'a}
```
<img width="396" alt="Screen Shot 2020-11-19 at 08 57 56" src="https://user-images.githubusercontent.com/4534692/99698373-8d7fb900-2a45-11eb-8794-028b225791a1.png">

This react component is inline in a call to a arity1 function `showModal(. <Component ... />)` which might be relevant.
If I do the same in a more normal spot, at the bottom of my functional component, I get a similar behavior but with this type instead: 
```rescript
(
  string,
  ~props: option<ReactDOMRe.props>,
  array<React.element>
) => React.element
```
If I cmd+click it, it jumps to ReasonReact's `createElement` external function

**Comment by cristianoc** [comment]
Does it compile, and is it saved?

**Comment by bsansouci** [comment]
It doesn't compile no, because the variable doesn't exist
