### ISSUE TITLE
Autocomplete picks up module open inside line comments `//`.

### ISSUE THREAD

**Issue by bsansouci** [rescript-lang/rescript-editor-support#15]
I've added `module String = Js.String2` at the top of my file of common stuff a really long time ago, and the autocomplete isn't picking up on it. It's still giving me the functions inside the stdlib `String` module.

**Comment by cristianoc** [comment]
Seems to work for me, at least when tried on a standalone file.
Maybe this and other issues can investigated when the rescript-vscode extension with this is released.
In general, the assumption is that everything has been built (typically there's a watcher).
Then autocomplete uses the information from the current build, plus the current file being edited.
So the file last saved must compile successfully (for `module String = Js.String2` to be picked up), and the edit since saving would contain something like `String.`.

So:
1) `module String = Js.String2`
2) save and build (or use a watcher)
3) edit `String.`
Then autocomplete should work as expected.

**Comment by cristianoc** [comment]
Closing as does not repro easily at the moment. Can be reopened with a new repro bases on latest release.

**Comment by bsansouci** [comment]
Hey, sorry for the silence, iOS work became high priority for a bit! 
So I upgraded to 1.0.4, and I'm still having this issue.

Here are some steps I can use to repro every time. Before anything, you need to have your own module with `module Array = { include Js.Array2; }` (mine is called `Common.res`)

In a new file I just write this, and get the correct autocomplete:
<img width="585" alt="Screen Shot 2021-01-08 at 08 40 39" src="https://user-images.githubusercontent.com/4534692/104040993-31a3f780-518d-11eb-8436-9351b5358807.png">

Then I open `Common` and get the correct autocomplete:
<img width="617" alt="Screen Shot 2021-01-08 at 08 40 59" src="https://user-images.githubusercontent.com/4534692/104041021-3cf72300-518d-11eb-85a7-38ab2e912f3d.png">

But then the craziest thing happens, if I comment out `open Common` I still get the old autocomplete no matter what I do (I can restart vscode, and will get the same persistent issue).
<img width="591" alt="Screen Shot 2021-01-08 at 08 49 32" src="https://user-images.githubusercontent.com/4534692/104041810-70867d00-518e-11eb-9adf-f9faaf897b56.png">

Then I remove that commented out line, and everything goes back to normal.
<img width="595" alt="Screen Shot 2021-01-08 at 08 51 02" src="https://user-images.githubusercontent.com/4534692/104041943-a461a280-518e-11eb-839b-a2dc305ec794.png">

Another, probably separate, issue that took me a while to track down is the following (small note, my code compiles and behaves correctly here, only autocomplete is having issues).
I have this function, parsing JSON and getting an object back. If I annotate `data` with anything (here `string`), I get correct autocomplete.
<img width="596" alt="Screen Shot 2021-01-08 at 09 09 00" src="https://user-images.githubusercontent.com/4534692/104043774-2652cb00-5191-11eb-9508-32c28a2c7bc4.png">

But if I annotate it with a generic `'a`, I get incorrect autocomplete from that point in the code and below (within the same scope).
<img width="592" alt="Screen Shot 2021-01-08 at 09 12 24" src="https://user-images.githubusercontent.com/4534692/104044074-a11be600-5191-11eb-9798-d4bd201d409a.png">


I think I did something along these lines, at the top level scope, which is why I'm getting issues at times. I'll work on removing these `'a`, but since this all compiles fine I'm surprised that these runtime cast throw off the autocomplete.

**Comment by cristianoc** [comment]
Here's what's going on. Autocomplete parses the source file backwards to look for `open`'s. There's some logic to exclude `/* stuff */` comments, but apparently not for line comments like:

```res
// open Belt
List.
```

**Comment by cristianoc** [comment]
For the second issue, it looks like single quotes are interpreted as string terminators, so `'a` is interpreted as an unterminated string.

**Comment by bsansouci** [comment]
Thanks for fixing! Super appreciate it :)

**Comment by cristianoc** [comment]
@bsansouci thank you for digging in and figuring out how to repro these corner cases.
