### ISSUE TITLE
Same function appears multiple times in the autocomplete menu

### ISSUE THREAD

**Issue by bsansouci** [rescript-lang/rescript-editor-support#16]
One of these is an external function, the other just a random optional value.
<img width="956" alt="Screen Shot 2020-11-19 at 09 27 45" src="https://user-images.githubusercontent.com/4534692/99701587-7e9b0580-2a49-11eb-8cb5-ce87b9e8e0ea.png">

**Comment by chenglou** [comment]
Does this still repro?

**Comment by bsansouci** [comment]
Nope!
