### ISSUE TITLE
Icons in autocomplete dropdown are a bit obscure

### ISSUE THREAD

**Issue by bsansouci** [rescript-lang/rescript-editor-support#20]
I'm not sure we can solve this issue, because I'm sure it's hard to find icons that are intuitive, but I don't really know the icons mean. If we get to choose, maybe we could use something like "T" for Type, "F" for function and "M" for module? Or even a 3-4 letter thing like `Type`, `Func`, `Mod`

<img width="1049" alt="Screen Shot 2020-11-20 at 09 09 39" src="https://user-images.githubusercontent.com/4534692/99829293-f97b2380-2b10-11eb-9193-71c2aed6340a.png">

**Comment by cristianoc** [comment]
Not sure they can be changed. These are determined by numbers specifying the kind of items in the protocol.
