### ISSUE TITLE
Go to definition on closing tag jsx.

### ISSUE THREAD

**Issue by IwanKaramazow** [rescript-lang/rescript-editor-support#26]
`<ReasonCompilerDocsLayout> content </ReasonCompilerDocsLayout>`

When the cursor is on the `</ReasonCompilerDocsLayout>`, the dump command returns an empty result.

**Comment by cristianoc** [comment]
There's no place in the AST corresponding to the closing tag: it disappears after parsing.
The opening tag corresponds to several elements in the AST, and the editor has to heuristically find the `make` function out of those.
If one wants something corresponding to both opoening and closing tags, then one would e.g. 2 copies of `make` in the AST, or a special mechanism (e.g. attributes) to signal the location of the closing tag. One positive aspect of a special mechanism would be to make the heuristic less magic.

**Comment by IwanKaramazow** [comment]
I could drop extra attributes in the AST if desired. Not sure how scalable this is depending on how much other "stuff" needs to be added in the future.

**Comment by cristianoc** [comment]
I think we can leave it for now, and avoid the extra complexity.
