### ISSUE TITLE
Switch PrintType.re to syntax outcome printer.

### ISSUE THREAD

**Issue by IwanKaramazow** [rescript-lang/rescript-editor-support#33]
`PrintType.re` currently uses some custom code to print types. The outcome printer from the syntax repo implements the same functionality: https://github.com/rescript-lang/syntax/blob/master/src/res_outcome_printer.ml and has tests.
To reduce complexity and provide a better printing experience for the user we should switch to the outcome printer of the syntax repo. Types can be converted to the `Outcometree` with the compiler-libs if I recall correctly.

**Comment by amiralies** [comment]
Should we use syntax repo as a submodule for this or just vendor desired modules?

**Comment by cristianoc** [comment]
The missing cases currently fall back to `Printtyp.type_expr`, which is implemented in the compiler as:

```ocaml
let typexp sch ppf ty =
  !Oprint.out_type ppf (tree_of_typexp sch ty)

let type_expr ppf ty = typexp false ppf ty
```

So one would use the same logic but replace `Oprint.out_type`.
