### ISSUE TITLE
Convert doc comment codes to rescript on the fly

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/rescript-editor-support#45]
See https://github.com/rescript-lang/rescript-compiler/issues/4872

for doing that we need to vendor `rescript-lang/syntax` (this affects bundle size).
we may want to introduce new apis to `Res_multi_printer` for converting from string to string, currently we need to create tmp files.

**Comment by cristianoc** [comment]
The current thinking is that doc comments will be written in markdown format, and using Rescript examples.
This should let us avoid introducing conversion, and remove the ad-hoc odoc parsing too (e.g. https://github.com/rescript-lang/rescript-editor-support/issues/17).

**Comment by amiralies** [comment]
Closing this fornow . since we are going to write docs in markdown.
