### ISSUE TITLE
Update syntax cf. pretty outcome printing of uncurried function types

### ISSUE THREAD

**Issue by IwanKaramazow** [rescript-lang/rescript-editor-support#46]
See https://github.com/rescript-lang/syntax/pull/214

This is relevant for editor tooling where types are displayed on hover:

**before**
```rescript
Js.Fn.arity3<(int, int, int) => int>
```

**after**
```rescript
(. int, int, int) => int
```

**Comment by IwanKaramazow** [comment]
Also not sure if we need to display the reference to `@unboxed @unboxed type arity3<'a> …`
<img width="364" alt="image" src="https://user-images.githubusercontent.com/10634678/103207201-0bb16400-48fe-11eb-8e23-6d5344751cc3.png">

**Comment by cristianoc** [comment]
Done in https://github.com/rescript-lang/rescript-editor-support/commit/51773c6e89b60b0ddd84bac0f61525d0fb0c2c68
