### ISSUE TITLE
rescript-editor-support.exe processes eating cpu

### ISSUE THREAD

**Issue by ruifortes** [rescript-lang/rescript-editor-support#53]
Hi.
I'm using windows 10 normally with multiple vscode instances opened.
I start hearing the cpu fan and then notice a lot of "rescript-editor-support.exe" processes were the cause.
After closing all vscode instances these processes don't end and I need to manually end them

**Comment by chenglou** [comment]
Thanks for the report. Closed in favor of https://github.com/rescript-lang/rescript-vscode/issues/43

**Comment by ruifortes** [comment]
Ups...missed that one. Sorry!
