### ISSUE TITLE
[Feature request]: Go to type definition

### ISSUE THREAD

**Issue by fhammerschmidt** [rescript-lang/rescript-editor-support#54]
Jump to definition works, but what would be equally great is "Go to type definition".

**Comment by cristianoc** [comment]
This should be working already, from `t` in `pair` should jump to the type definition.

```res
type t = int

type pair = (t, t)
```

**Comment by fhammerschmidt** [comment]
In this simple case, it does. Unfortunately it does not seem to work anymore, when t is inside another module or file:

```res
module Test = {
  type t = int
}

type pair = (Test.t, Test.t)
```
