### ISSUE TITLE
Js.arity<..> should not be visible

### ISSUE THREAD

**Issue by ryyppy** [rescript-lang/rescript-editor-support#62]
I just upgraded our vim setup to rescript-vscode 1.0.6, which comes with the updated ReScript Outcomeprinter.

Right now, when writing code like this:

```
let callbackU = (. a) => Js.log(a)

callbackU //<-- running dump on here
```

the triggered type hint output with coc-vim looks like this:

![image](https://user-images.githubusercontent.com/1121889/107850200-f71f2180-6e00-11eb-80a8-42732ec43731.png)

Running the `editor-support` binary directly shows me this:

~~~
Pos (l:c): 56:9
```rescript
(. 'a) => unit
```

```rescript
@unboxed @unboxed type arity1<'a> = {\"I1": 'a}
```

<root>/src/bar.res
~~~

**Expected output:**

Since `type arity1` is an implementation detail, I'd only be interested in the syntax sugared `(. 'a) => unit` representation. IMO this extra `@unboxed @unboxed type arity1<'a> = {\"I1": 'a}` codesnippet should not show up, but I guess this has something to do with how alias showing works?

**Comment by ryyppy** [comment]
Update: I did something wrong in my coc-vim setup, so it picked up the wrong editor-support binary.

It now shows me this:

![image](https://user-images.githubusercontent.com/1121889/107850427-a6a8c380-6e02-11eb-829b-ac68615199f5.png)

I still think the extra alias is more confusing than it helps for most users.

**Comment by cristianoc** [comment]
https://github.com/rescript-lang/rescript-editor-support/pull/64/commits/68e8b1829bd0f93829dbe6131a490f21498acf76
