### ISSUE TITLE
Autocomplete available export when opening a Module

### ISSUE THREAD

**Issue by montogeek** [rescript-lang/rescript-editor-support#66]
Hi!

It would be good to offer autocompletion for all possible exports right after opening a module.

For example for this code, if you use Cmd+Space in the next line after `open MaterialUi`, it should show all possible exports from MaterialUi.
```
@react.component
let make = () => {
  open MaterialUi; 
  <div> {React.string("Hello World")} </div>
}
```

**Comment by cristianoc** [comment]
It should work if you type the first letter of the module. Does it work for you?
And, `MaterialUi.` should list all the possible modules if one has no idea of what the possibilities are.

**Comment by montogeek** [comment]
@cristianoc You are right, it is working now.
