### ISSUE TITLE
Pipe (->) autocompletion for built-in types.

### ISSUE THREAD

**Issue by cristianoc** [rescript-lang/rescript-editor-support#98]
- `array<>` could by default autocomplete from `Js.Array2.t<>`
- notice `Belt.Array.t<>` is not defined, an oversight -- can be added.
- `list<>` there's no module `Js.List2` at the moment, which seems inconsistent.
- `string` not sure but see https://github.com/rescript-lang/rescript-editor-support/issues/99
- `option<>`

**Comment by hoichi** [comment]
> there's no module Js.List2 at the moment, which seems inconsistent.

But `Js` namespace is for zero-cost bindings to functions/methods built into JS engines, and there are no built-in linked lists in JS.
