### ISSUE TITLE
-> Autocompletion breaks "." autocompletion

### ISSUE THREAD

**Issue by ryyppy** [rescript-lang/rescript-editor-support#99]
Excerpt from [this forum post](https://forum.rescript-lang.org/t/ann-new-editor-plugin-release-for-vscode-1-0-7-vim-1-4-0-autocompletion-for-and-function-labels/1394/7?u=ryyppy) by @alexeygolev:

>The “->” autocomplete works in vim as described. However “normal” autocompletion for “->” is broken.
>
> "hello"->Js. // no completion prompt here
> Some("hello")->Option. // no completion prompt here
>
> Pinned to 1.3.0 as I’d rather have the above. Not sure if this is the intended behaviour
> Update: The same happens in VSCode.

So the desired behavior would be: 

On `>`, trigger the function autocompletion, and on every further `.`, use the module content autocompletion.

**Comment by cristianoc** [comment]
There's no `->` autocomplete yet for constants such as `"hello"`, only for variables at the moment.

The workaround for those examples for now is to leave a space `-> Js.`.

I guess when `->` autocomplete does not lead to anything, it makes sense to handle `.` in the normal way.

Side comment, after having played with autocomplete for a while, I am changing my uses of `->`. Before I used any time it was possible, now I only use it when the lhs belongs to a module that is collection-style: i.e. that has a main type e.g. `t` and a bunch of functions on it.

**Comment by alexeygolev** [comment]
> There's no `->` autocomplete yet for constants such as `"hello"`, only for variables at the moment.
> 
> The workaround for those examples for now is to leave a space `-> Js.`.

I don't think this is the case:

```
let a = Some(a)

a->Option. // no completion
```
The best workaround for me is just staying on the previous version. It worked perfectly

> I guess when `->` autocomplete does not lead to anything, it makes sense to handle `.` in the normal way.
> 
> Side comment, after having played with autocomplete for a while, I am changing my uses of `->`. Before I used any time it was possible, now I only use it when the lhs belongs to a module that is collection-style: i.e. that has a main type e.g. `t` and a bunch of functions on it.

I have no idea what you mean to be honest. Modules like `Option` and `Js.String` work with built-in types so they don't have a type `t`. Does this mean that you wouldn't use `->` for those modules?

**Comment by cristianoc** [comment]
`Option` and `Js.String` are about one specific type, even though they don't define it. That's what I mean.
